<?php
function generate_payment_email($student, $payment_data, $due_amount = 0, $is_partial = false) {
    $n = $student['first_name'] . ' ' . $student['last_name'];
    $amt = number_format($payment_data['amount'], 2);
    $pdate = date('M d, Y', strtotime($payment_data['payment_date']));
    $pmonth = isset($payment_data['payment_month']) ? date('F Y', strtotime($payment_data['payment_month'] . '-01')) : date('F Y');
    $pmethod = ucfirst($payment_data['payment_method']);
    $stat = ucfirst($payment_data['status']);
    $s = strtolower($payment_data['status']);
    
    $cfg = ['pending' => ['bg'=>'#ffc107','icon'=>'⏳','title'=>'Payment Pending','sbg'=>'#fff3cd','sc'=>'#856404','sb'=>'#ffeaa7','msg'=>'Payment received, under review.','ty'=>'We will notify once processed! 📋','ai'=>'Verification takes 1-2 business days.'],
            'completed' => ['bg'=>'#007bff','icon'=>'💳','title'=>'Payment Confirmation','sbg'=>'#d4edda','sc'=>'#155724','sb'=>'#c3e6cb','msg'=>'Payment successfully processed.','ty'=>'Thank you! 🎉','ai'=>'Contact support if you have questions.'],
            'cancelled' => ['bg'=>'#dc3545','icon'=>'❌','title'=>'Payment Cancelled','sbg'=>'#f8d7da','sc'=>'#721c24','sb'=>'#f5c6cb','msg'=>'Payment cancelled per request.','ty'=>'Cancelled. 💳','ai'=>'Contact support if this was an error.']][$s] ?? 
            ['bg'=>'#007bff','icon'=>'💳','title'=>'Payment Confirmation','sbg'=>'#d4edda','sc'=>'#155724','sb'=>'#c3e6cb','msg'=>'Payment successfully processed.','ty'=>'Thank you! 🎉','ai'=>'Contact support if you have questions.'];
    
    if ($is_partial && $s === 'pending') {
        $cfg['title'] = 'Partial Payment Received';
        $cfg['msg'] = 'Partial payment received and recorded.';
        $cfg['ty'] = 'Thank you! Complete remaining balance soon. 💳';
        $cfg['ai'] = 'Remaining: ₹' . number_format($due_amount, 2) . '. Complete payment to finish fees.';
    }
    
    $html = "<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial;line-height:1.6;color:#333;margin:0;padding:0;background:#f8f9fa}.email-container{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.email-header{background:linear-gradient(135deg,".$cfg['bg'].",#0056b3);color:#fff;padding:25px 20px;text-align:center}.email-header h1{margin:0;font-size:24px}.email-header p{margin:5px 0 0 0;font-size:14px;opacity:0.9}.email-content{padding:30px 20px}.message-box{background-color:".$cfg['sbg'].";color:".$cfg['sc'].";padding:15px;border-radius:8px;border:1px solid ".$cfg['sb'].";margin:20px 0}.details-section{background:#f8f9fa;border:1px solid #dee2e6;border-radius:8px;padding:20px;margin:20px 0}.detail-row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e9ecef}.detail-row:last-child{border-bottom:none}.detail-label{font-weight:600;color:#495057}.detail-value{color:#007bff;font-weight:500}.amount-highlight{font-size:20px;color:#28a745;font-weight:bold}.status-badge{display:inline-block;padding:5px 12px;border-radius:20px;font-size:14px;font-weight:bold;text-transform:uppercase}.download-section{background:#f8f9fa;padding:20px;border-radius:8px;margin:20px 0;border-left:4px solid #007bff}.download-link{color:#007bff;text-decoration:none;font-weight:500}.thank-you{font-size:16px;color:#28a745;font-weight:600;margin:20px 0;text-align:center}.email-footer{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='email-container'><div class='email-header'><h1>".$cfg['icon']." ".$cfg['title']."</h1></div><div class='email-content'><p>Payment Details:</p><div class='message-box'>".$cfg['msg']."</div><div class='details-section'><div class='detail-row'><span class='detail-label'>Amount:</span><span class='detail-value amount-highlight'>₹".$amt."</span></div><div class='detail-row'><span class='detail-label'>Date:</span><span class='detail-value'>".$pdate."</span></div><div class='detail-row'><span class='detail-label'>Payment Month:</span><span class='detail-value'>".$pmonth."</span></div><div class='detail-row'><span class='detail-label'>Method:</span><span class='detail-value'>".$pmethod."</span></div><div class='detail-row'><span class='detail-label'>Status:</span><span class='detail-value'><span class='status-badge'>".$stat."</span></span></div>".($is_partial?"<div class='detail-row'><span class='detail-label'>Due:</span><span class='detail-value amount-highlight'>₹".number_format($due_amount,2)."</span></div>":"")."</div>";
    
    if(isset($payment_data['payment_code'])){
        $html .= "<div class='download-section'><p>Download Receipt: <a href='http://yogaculture.kesug.com/recipt?code=".urlencode($payment_data['payment_code'])."' class='download-link'>Download</a></p></div>";
    }
    
    $html .= "<div class='thank-you'>".$cfg['ty']."</div><p>".$cfg['ai']."</p><div class='email-footer'><p>© ".date('Y')." Student Payment System</p></div></div></div></body></html>";
    return $html;
}

function generate_username_change_email($u,$n,$o){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#007bff,#0056b3);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#e7f3ff;color:#084c7d;padding:15px;border-radius:8px;border:1px solid #b8daff;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:#007bff;text-align:center;margin:20px 0;letter-spacing:3px}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>🔐 Username Change</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Change username to <strong>".htmlspecialchars($n)."</strong>. Use OTP:</div><div class='otp'>".$o."</div><p>Valid for 5 minutes. If not requested, ignore.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_email_change_email($u,$ne,$o){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#007bff,#0056b3);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#e7f3ff;color:#084c7d;padding:15px;border-radius:8px;border:1px solid #b8daff;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:#007bff;text-align:center;margin:20px 0;letter-spacing:3px}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>🔐 Email Change</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Change email to <strong>".htmlspecialchars($ne)."</strong>. Use OTP:</div><div class='otp'>".$o."</div><p>Valid for 5 minutes. If not requested, ignore.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_password_otp_email($u,$o,$r=false){$t=$r?'Reset':'Change';$c=$r?'#dc3545':'#007bff';$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,".$c.",#0056b3);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#e7f3ff;color:#084c7d;padding:15px;border-radius:8px;border:1px solid #b8daff;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:".$c.";text-align:center;margin:20px 0;letter-spacing:3px}.wrn{background:#fff3cd;color:#856404;padding:15px;border-radius:8px;border:1px solid #ffeaa7;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>🔑 Password ".$t."</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Password ".$t." OTP:</div><div class='otp'>".htmlspecialchars($o)."</div><div class='wrn'><p><strong>⚠️ Valid 5 min. Don't share. For security, one-time use only.</strong></p></div><p>".$t." your password now.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_password_reset_success_email($u){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#1e7e34);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>✅ Reset Successful</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Password reset successful. If not done, contact support.</div></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_registration_otp_email($u,$e,$o){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#1e7e34);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:#28a745;text-align:center;margin:20px 0;letter-spacing:3px}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>🎉 Registration Verification</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Complete registration with OTP:</div><div class='otp'>".$o."</div><p>Valid for 10 minutes. If not requested, ignore.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_account_deletion_email($u,$o){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#dc3545,#c82333);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#f8d7da;color:#721c24;padding:15px;border-radius:8px;border:1px solid #f5c6cb;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:#dc3545;text-align:center;margin:20px 0;letter-spacing:3px}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>⚠️ Delete Account</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>Confirm account deletion (removes all data). Use OTP:</div><div class='otp'>".$o."</div><p>Valid for 5 minutes. If not requested, ignore.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_username_change_success_email($u,$n){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#1e7e34);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>✅ Username Changed</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><p>New username: <strong>".htmlspecialchars($n)."</strong></p><p>Use this for next login.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_email_change_success_email($u){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#1e7e34);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>✅ Email Changed</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><p>Email updated. Future notifications sent to new address.</p><div class='msg'>⚠️ If not done by you, contact support.</div></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_password_change_confirmation_email($u){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#1e7e34);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>✅ Changed</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='msg'>✓ Password changed. Use new password to login next time. If not done, reset immediately.</div></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_account_deletion_success_email($u){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#ffc107,#e0a800);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#fff3cd;color:#856404;padding:15px;border-radius:8px;border:1px solid #ffeaa7;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>⚠️ Account Deleted</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><p>Account permanently deleted. Cannot be undone. Removed: Profile, Students, Payments.</p><p>Register again to use system.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_profile_error_notification_email($u,$a,$e){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#dc3545,#c82333);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.err{background:#f8d7da;color:#721c24;padding:15px;border-radius:8px;border:1px solid #f5c6cb;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>❌ Error</h1></div><div class='con'><p>Dear ".htmlspecialchars($u).",</p><div class='err'><p><strong>Action:</strong> ".htmlspecialchars($a)."</p><p><strong>Error:</strong> ".htmlspecialchars($e)."</p></div><p>Try again or contact support.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_student_added_email($s){
    $sn = htmlspecialchars(trim(($s['first_name'] ?? '') . ' ' . ($s['last_name'] ?? '')));
    $si = htmlspecialchars($s['student_id'] ?? '');
    $c = htmlspecialchars($s['course'] ?? '');
    $ct = htmlspecialchars($s['class_type'] ?? '');
    $ad = !empty($s['admission_date']) ? date('M d, Y', strtotime($s['admission_date'])) : '';
    $f = isset($s['fee_amount']) ? number_format($s['fee_amount'], 2) : '';
    $af = isset($s['admission_fees']) && $s['admission_fees'] !== '' ? number_format($s['admission_fees'], 2) : '';
    $isUpdate = !empty($s['is_update']);
    $statusText = $isUpdate ? 'Student record updated successfully.' : 'Student record created successfully.';
    $actionText = $isUpdate ? 'Updated' : 'Created';
    $h = "<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#007bff,#0056b3);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#e7f3ff;color:#084c7d;padding:15px;border-radius:8px;border:1px solid #b8daff;margin:20px 0}.detail{background:#f8f9fa;border:1px solid #dee2e6;border-radius:8px;padding:20px;margin:20px 0}.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e9ecef}.row:last-child{border-bottom:none}.label{font-weight:600;color:#495057}.value{color:#007bff;font-weight:500}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>" . ($isUpdate ? 'Student Updated' : 'New Student Created') . "</h1></div><div class='con'><p>Dear ".$sn.",</p><p>".$statusText."</p><div class='msg'><p><strong>Status:</strong> " . $actionText . "</p></div><div class='detail'><div class='row'><span class='label'>ID:</span><span class='value'>".$si."</span></div>".
        (!empty($c) ? "<div class='row'><span class='label'>Course:</span><span class='value'>".$c."</span></div>" : "").
        (!empty($ct) ? "<div class='row'><span class='label'>Class Type:</span><span class='value'>".$ct."</span></div>" : "").
        (!empty($ad) ? "<div class='row'><span class='label'>Admission Date:</span><span class='value'>".$ad."</span></div>" : "").
        ($f !== '' ? "<div class='row'><span class='label'>Fee Amount:</span><span class='value'>₹".$f."</span></div>" : "").
        ((!$isUpdate && $af !== '') ? "<div class='row'><span class='label'>Admission Fees:</span><span class='value'>₹".$af."</span></div>" : "").
    "</div></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";
    return $h;
}

function generate_login_otp_email($u,$e,$o){$h="<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body{font-family:Arial;background:#f8f9fa;margin:0;padding:0}.c{max-width:600px;margin:20px auto;background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.hdr{background:linear-gradient(135deg,#28a745,#20c997);color:#fff;padding:25px 20px;text-align:center}.hdr h1{margin:0;font-size:24px}.con{padding:30px 20px}.msg{background:#d4edda;color:#155724;padding:15px;border-radius:8px;border:1px solid #c3e6cb;margin:20px 0}.otp{font-size:28px;font-weight:bold;color:#28a745;text-align:center;letter-spacing:3px;background:#f8f9fa;padding:15px;border-radius:8px;border:2px dashed #28a745;margin:20px 0}.wrn{background:#fff3cd;color:#856404;padding:15px;border-radius:8px;border:1px solid #ffeaa7;margin:20px 0}.ftr{margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;text-align:center;color:#6c757d;font-size:14px}</style></head><body><div class='c'><div class='hdr'><h1>🔐 Login</h1></div><div class='con'><p>Hello ".htmlspecialchars($u).",</p><div class='msg'><p><strong>Login Verification Required</strong></p><p>Use OTP to complete login:</p></div><div class='otp'>".htmlspecialchars($o)."</div><div class='wrn'><p><strong>⚠️ Valid 5 min. Don't share. One-time use.</strong></p></div><p>If not requested, ignore.</p></div><div class='ftr'><p>© ".date('Y')." Student Payment System</p></div></div></body></html>";return $h;}

function generate_password_reset_otp_email($u,$e,$o){return generate_password_otp_email($u,$o,true);}
?>